-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users Table (Supabase handles auth.users, but we might need a public profiles table or just use auth metadata. 
-- For simplicity and to match existing logic, we'll create a public.users table that links to auth.users or just stands alone if they aren't using Supabase Auth fully yet.
-- However, the user said "store the url and key... i have written connection". 
-- Best practice with Supabase is to use their Auth system. 
-- But to minimize friction, I'll create a public users table that mirrors the old one, 
-- OR better, I'll assume we will use Supabase Auth and I'll create a 'profiles' table.
-- Given the user wants to "copy paste the query", I should stick to a structure that works easily.
-- I will create standard tables.

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    image TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image TEXT,
    stock INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Linking to Supabase Auth User
    total_amount DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    shipping_address TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    variant_info TEXT
);

-- Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Wishlist Table
CREATE TABLE IF NOT EXISTS wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(user_id, product_id)
);

-- Insert Categories
INSERT INTO categories (name, slug, image) VALUES
('Vortex', 'vortex', 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991'),
('Hoodies and Sweatshirt', 'hoodies-and-sweatshirt', 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816'),
('Jackets', 'jackets', 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065'),
('T-shirt', 't-shirt', 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787'),
('Bottoms', 'bottoms', 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991'),
('Headwear', 'headwear', 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816'),
('Accessories', 'accessories', 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065');

-- Insert Products (30 items)
-- We will use a DO block to generate data, but standard SQL is more portable for the query editor if they don't support PL/pgSQL blocks easily (Supabase does, but simple INSERTs are safer).
-- I'll just generate 30 insert statements.

INSERT INTO products (category_id, name, slug, description, price, image, stock) VALUES
(1, 'Vortex Alpha', 'vortex-alpha', 'Premium Vortex clothing item.', 49.99, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 100),
(2, 'Classic Hoodie', 'classic-hoodie', 'Comfortable and warm hoodie.', 59.99, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 100),
(3, 'Urban Jacket', 'urban-jacket', 'Stylish jacket for city life.', 89.99, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 50),
(4, 'Essential Tee', 'essential-tee', 'Everyday cotton t-shirt.', 24.99, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 200),
(5, 'Cargo Bottoms', 'cargo-bottoms', 'Durable cargo pants.', 54.99, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 80),
(6, 'Snapback Cap', 'snapback-cap', 'Adjustable snapback cap.', 19.99, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 150),
(7, 'Leather Belt', 'leather-belt', 'Genuine leather belt.', 29.99, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 100),
(1, 'Vortex Beta', 'vortex-beta', 'Another great Vortex item.', 55.00, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 90),
(2, 'Zip-Up Sweatshirt', 'zip-up-sweatshirt', 'Easy to wear zip-up.', 65.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 85),
(3, 'Bomber Jacket', 'bomber-jacket', 'Classic bomber style.', 95.00, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 40),
(4, 'Graphic Tee', 'graphic-tee', 'T-shirt with cool graphics.', 29.99, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 180),
(5, 'Joggers', 'joggers', 'Comfortable joggers for lounging.', 45.00, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 120),
(6, 'Beanie', 'beanie', 'Warm knitted beanie.', 15.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 200),
(7, 'Wristband', 'wristband', 'Stylish wrist accessory.', 9.99, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 300),
(1, 'Vortex Gamma', 'vortex-gamma', 'Top tier Vortex gear.', 60.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 70),
(2, 'Oversized Hoodie', 'oversized-hoodie', 'Trendy oversized fit.', 70.00, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 60),
(3, 'Denim Jacket', 'denim-jacket', 'Rugged denim material.', 80.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 55),
(4, 'V-Neck Tee', 'v-neck-tee', 'Sharp V-neck cut.', 22.00, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 150),
(5, 'Chinos', 'chinos', 'Smart casual chinos.', 50.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 90),
(6, 'Bucket Hat', 'bucket-hat', 'Summer vibes bucket hat.', 25.00, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 110),
(7, 'Socks Pack', 'socks-pack', 'Pack of 3 premium socks.', 12.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 250),
(1, 'Vortex Delta', 'vortex-delta', 'Performance Vortex wear.', 52.00, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 80),
(2, 'Pullover', 'pullover', 'Classic pullover style.', 58.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 95),
(3, 'Windbreaker', 'windbreaker', 'Lightweight wind protection.', 75.00, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 65),
(4, 'Long Sleeve Tee', 'long-sleeve-tee', 'Perfect for layering.', 28.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 130),
(5, 'Shorts', 'shorts', 'Casual summer shorts.', 35.00, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 140),
(6, 'Visor', 'visor', 'Sporty sun visor.', 18.00, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.00.59PM_1_ab4f6465-0a09-4560-9021-e9b47691e87a_533x.jpg?v=1760183065', 80),
(7, 'Scarf', 'scarf', 'Winter warm scarf.', 22.00, 'https://bloza.shop/cdn/shop/files/ADC029CC-BBB7-4705-88C5-A67E1D202B48_533x.jpg?v=1751605787', 100),
(1, 'Vortex Omega', 'vortex-omega', 'Ultimate Vortex collection.', 99.99, 'https://bloza.shop/cdn/shop/files/WhatsAppImage2025-10-11at3.01.09PM_533x.jpg?v=1760183991', 30),
(2, 'Fleece Hoodie', 'fleece-hoodie', 'Extra soft fleece.', 62.00, 'https://bloza.shop/cdn/shop/files/WhatsApp_Image_2025-10-02_at_3.13.28_PM_533x.jpg?v=1759403816', 75);

-- Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlist ENABLE ROW LEVEL SECURITY;

-- Create Policies (Public Read for Products/Categories)
CREATE POLICY "Public categories are viewable by everyone" ON categories FOR SELECT USING (true);
CREATE POLICY "Public products are viewable by everyone" ON products FOR SELECT USING (true);

-- Auth Policies
CREATE POLICY "Users can view their own orders" ON orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own orders" ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own wishlist" ON wishlist FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own wishlist" ON wishlist FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own wishlist" ON wishlist FOR DELETE USING (auth.uid() = user_id);

